- clean: ['~']

- defaults:
    link:
        create: true

- link:
    ~/.bash_profile: .bash_profile
    ~/.bashrc: .bashrc
    ~/.bash_logout: .bash_logout
    ~/.fehbg: .fehbg
    ~/.zshrc: .zshrc
    ~/.Xresources: .Xresources
    ~/.tmux.conf: .tmux.conf
    ~/.config/i3:
        path: i3/
    ~/.config/i3blocks:
        path: i3blocks/
    ~/.config/rofi:
        path: rofi/
    ~/.config/nvim:
        path: nvim/
    ~/.config/dunst:
        path: dunst/
    ~/.config/gtk-3.0/settings.ini:
        path: gtk-3.0/settings.ini
        force: true
    ~/.oh-my-zsh:
        path: oh-my-zsh/
